lotj.comlinkInfo.registerComlink(matches.comlink, matches.channel, matches.encryption)
echo("\n")
lotj.comlinkInfo.log("Stored comlink: "..matches.comlink)
lotj.comlinkInfo.log("Stored channel: "..matches.channel)
lotj.comlinkInfo.log("Stored encryption: "..matches.encryption)
